apiVersion: v1
kind: Service
metadata:
  name: office-deployment
  namespace: office
spec:
  type: LoadBalancer
  selector:
    app: office-deployment
  ports:
    - port: 10443
      targetPort: 10443
